### ISSUE TITLE
Create Routing table 

### ISSUE THREAD

**Issue by TejasRajeshirke** [tejas161994/nodeexpressFile#3]
## Routing Table for the following ##
1. Addition 
2. Substraction
3. Multiplication
4. Division

## The previous path should have _mathematicaloperation_ ##

Example:
```
Website/mathematicaloperation/addition
Website/mathematicaloperation/multiplication
```

**Comment by Nahdus** [comment]
is this complete?

**Comment by Nahdus** [comment]
@tejas161994 ??
